// <auto-generated />
namespace _2013100788_PER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lul : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lul));
        
        string IMigrationMetadata.Id
        {
            get { return "201706080834000_lul"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
